GoogleToken: QUFFLUhqbWg4QWY3OXBVOEE2Wml0VmRpVFdub21jM2psQXw=
Streamers:
  Delaney:
    Url: UCee3jrGUdb2ovrE7v4ncH3Q
    Test: testtwitch
  Fireship:
    Url: UCsBjURrPoezykLs9EqgamOA
    Test: testyoutube
  # Tew:
  #   Url: UCpfWIOPj5ZjgaY42ES_VmOg
  #   Test: testyoutube
