GoogleToken: QUFFLUhqbWg4QWY3OXBVOEE2Wml0VmRpVFdub21jM2psQXw=
Streamers:
  Delaney:
    Url: UCee3jrGUdb2ovrE7v4ncH3Q
    Platform: Youtube
  Fireship:
    Url: UCsBjURrPoezykLs9EqgamOA
    Platform: youtube
  md:
    Url: maximilian_dood
    Platform: Twitch
  go1:
    Url: cyclops_go1
    Platform: Twitch